var annotated_dup =
[
    [ "AnalogInput", "class_analog_input.html", "class_analog_input" ],
    [ "BlockPort", "class_block_port.html", "class_block_port" ],
    [ "Button", "class_button.html", "class_button" ],
    [ "Channel", "class_channel.html", "class_channel" ],
    [ "CircleGenerator", "class_circle_generator.html", "class_circle_generator" ],
    [ "Eibotboard", "class_eibotboard.html", "class_eibotboard" ],
    [ "Encoder", "class_encoder.html", "class_encoder" ],
    [ "FourTrackPlayer", "class_four_track_player.html", "class_four_track_player" ],
    [ "FourTrackRecorder", "class_four_track_recorder.html", "class_four_track_recorder" ],
    [ "GCodeInterface", "class_g_code_interface.html", "class_g_code_interface" ],
    [ "InputPort", "class_input_port.html", "class_input_port" ],
    [ "KinematicsCoreXY", "class_kinematics_core_x_y.html", "class_kinematics_core_x_y" ],
    [ "KinematicsFiveBarForward", "class_kinematics_five_bar_forward.html", "class_kinematics_five_bar_forward" ],
    [ "KinematicsPolarToCartesian", "class_kinematics_polar_to_cartesian.html", "class_kinematics_polar_to_cartesian" ],
    [ "OutputPort", "class_output_port.html", "class_output_port" ],
    [ "PathLengthGenerator2D", "class_path_length_generator2_d.html", "class_path_length_generator2_d" ],
    [ "PathLengthGenerator3D", "class_path_length_generator3_d.html", "class_path_length_generator3_d" ],
    [ "PositionGenerator", "class_position_generator.html", "class_position_generator" ],
    [ "RecorderTrack", "class_recorder_track.html", null ],
    [ "RPC", "class_r_p_c.html", "class_r_p_c" ],
    [ "ScalingFilter1D", "class_scaling_filter1_d.html", "class_scaling_filter1_d" ],
    [ "ScalingFilter2D", "class_scaling_filter2_d.html", "class_scaling_filter2_d" ],
    [ "ThresholdGenerator", "class_threshold_generator.html", "class_threshold_generator" ],
    [ "TimeBasedInterpolator", "class_time_based_interpolator.html", "class_time_based_interpolator" ],
    [ "VelocityGenerator", "class_velocity_generator.html", "class_velocity_generator" ],
    [ "WaveGenerator1D", "class_wave_generator1_d.html", "class_wave_generator1_d" ]
];