var searchData=
[
  ['c_20connect_20and_20select_20the_20board_0',['C. Connect and Select the Board',['../getting_started.html#autotoc_md37',1,'']]],
  ['calculate_20the_20reference_20voltage_1',['Calculate the Reference Voltage',['../stepasketch.html#autotoc_md9',1,'']]],
  ['cartesian_2',['&lt;a class=&quot;el&quot; href=&quot;polar_to_cartesian_2polar_to_cartesian_8ino-example.html&quot;&gt;Polar to Cartesian&lt;/a&gt;',['../examples_kinematics.html#autotoc_md120',1,'']]],
  ['cartesian_203d_20printer_3',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_2polar_cartesian_3dprinter_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md116',1,'']]],
  ['cartesian_203d_20printer_20with_20extrusion_4',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_extrusion_2polar_cartesian_3dprinter_extrusion_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer with Extrusion&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md117',1,'']]],
  ['categories_5',['Categories',['../documentation.html#autotoc_md81',1,'Categories'],['../examples.html#autotoc_md87',1,'Categories'],['../code_examples.html#autotoc_md86',1,'Example Categories']]],
  ['channel_6',['Channel',['../class_channel.html',1,'Channel'],['../stepasketch.html#autotoc_md16',1,'Channel']]],
  ['channels_7',['Channels',['../group__channels.html',1,'Channels'],['../stepasketch.html#autotoc_md24',1,'Configure Channels']]],
  ['circlegenerator_8',['CircleGenerator',['../class_circle_generator.html',1,'']]],
  ['clay_203d_20printer_20texturizer_9',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_2clay_3dprinter_texturizer_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md114',1,'']]],
  ['clay_203d_20printer_20texturizer_20modularized_20v2_10',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_modularized_v2_2clay_3dprinter_texturizer_modularized_v2_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer Modularized V2&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md115',1,'']]],
  ['clay_203d_20printer_20variants_11',['Clay 3D Printer Variants',['../examples.html#autotoc_md91',1,'<a class="el" href="examples_clayprinter.html">Clay 3D Printer Variants</a>'],['../examples_clayprinter.html',1,'Clay 3D Printer Variants']]],
  ['clay_5f3dprinter_5ftexturizer_20clay_5f3dprinter_5ftexturizer_20ino_20clay_203d_20printer_20texturizer_12',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_2clay_3dprinter_texturizer_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md114',1,'']]],
  ['clay_5f3dprinter_5ftexturizer_20ino_20clay_203d_20printer_20texturizer_13',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_2clay_3dprinter_texturizer_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md114',1,'']]],
  ['clay_5f3dprinter_5ftexturizer_5fmodularized_5fv2_20clay_5f3dprinter_5ftexturizer_5fmodularized_5fv2_20ino_20clay_203d_20printer_20texturizer_20modularized_20v2_14',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_modularized_v2_2clay_3dprinter_texturizer_modularized_v2_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer Modularized V2&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md115',1,'']]],
  ['clay_5f3dprinter_5ftexturizer_5fmodularized_5fv2_20ino_20clay_203d_20printer_20texturizer_20modularized_20v2_15',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_modularized_v2_2clay_3dprinter_texturizer_modularized_v2_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer Modularized V2&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md115',1,'']]],
  ['clear_5finvert_16',['clear_invert',['../class_button.html#abc0a668359f51eb1453ea759d8bb3525',1,'Button']]],
  ['clearlowerthreshold_17',['clearLowerThreshold',['../class_threshold_generator.html#a5138b879ac51822745611494315558d8',1,'ThresholdGenerator']]],
  ['clearupperthreshold_18',['clearUpperThreshold',['../class_threshold_generator.html#a7dbe3c7ac94b27e206f4d198b130129f',1,'ThresholdGenerator']]],
  ['code_19',['Code',['../stepasketch.html#autotoc_md11',1,'']]],
  ['code_20examples_20',['Code Examples',['../code_examples.html',1,'documentation']]],
  ['code_20stepasketch_21',['&lt;a class=&quot;el&quot; href=&quot;gcode_stepasketch_2gcode_stepasketch_8ino-example.html&quot;&gt;G-Code Stepasketch&lt;/a&gt;',['../examples_plotting.html#autotoc_md110',1,'']]],
  ['components_22',['Core Components',['../group__core.html',1,'']]],
  ['components_23',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['concepts_24',['Concepts',['../examples.html#autotoc_md88',1,'<a class="el" href="examples_core.html">Core Concepts</a>'],['../highspeed.html#autotoc_md62',1,'Concepts']]],
  ['configuration_25',['Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md61',1,'High-Speed Frame Configuration']]],
  ['configure_20channels_26',['Configure Channels',['../stepasketch.html#autotoc_md24',1,'']]],
  ['configure_20encoders_27',['Configure Encoders',['../stepasketch.html#autotoc_md25',1,'']]],
  ['configure_20output_20ports_28',['Configure Output Ports',['../stepasketch.html#autotoc_md23',1,'']]],
  ['configure_20position_20generator_29',['Configure Position Generator',['../stepasketch.html#autotoc_md28',1,'']]],
  ['configure_20the_20button_30',['Configure the Button',['../stepasketch.html#autotoc_md27',1,'']]],
  ['configure_20the_20kinematics_31',['Configure the Kinematics',['../stepasketch.html#autotoc_md26',1,'']]],
  ['configuring_20the_20stepdance_20driver_20board_32',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['connect_20and_20select_20the_20board_33',['C. Connect and Select the Board',['../getting_started.html#autotoc_md37',1,'']]],
  ['connector_34',['Connector',['../taiss.html#autotoc_md80',1,'']]],
  ['connectors_35',['QWIIC Connectors',['../hardware.html#autotoc_md44',1,'']]],
  ['considerations_36',['Considerations',['../highspeed.html#autotoc_md63',1,'']]],
  ['control_20knob_20mounting_37',['Display and Control Knob Mounting',['../hardware.html#autotoc_md47',1,'']]],
  ['controller_20emulator_38',['Axidraw &quot;EBB&quot; Controller Emulator',['../hardware.html#autotoc_md60',1,'']]],
  ['controller_20emulator_20example_39',['Axidraw EBB Controller Emulator Example',['../ebb.html',1,'tutorials_docs']]],
  ['coordinate_20transforms_40',['Coordinate Transforms',['../examples.html#autotoc_md92',1,'<a class="el" href="examples_kinematics.html">Kinematics / Coordinate Transforms</a>'],['../examples_kinematics.html',1,'Kinematics / Coordinate Transforms']]],
  ['core_20components_41',['Core Components',['../group__core.html',1,'']]],
  ['core_20concepts_42',['&lt;a class=&quot;el&quot; href=&quot;examples_core.html&quot;&gt;Core Concepts&lt;/a&gt;',['../examples.html#autotoc_md88',1,'']]],
  ['core_20example_20sketches_43',['Core Example Sketches',['../examples_core.html',1,'code_examples']]],
  ['current_44',['Determine the Peak Motor Current',['../stepasketch.html#autotoc_md8',1,'']]],
  ['current_5fposition_45',['current_position',['../class_channel.html#a3c96c0b9aee1a6e7d9bb265ccb9c86e7',1,'Channel']]],
  ['currents_46',['Currents',['../examples_core.html#autotoc_md99',1,'<a class="el" href="set_motor_currents_2set_motor_currents_8ino-example.html">Set Motor Currents</a>'],['../stepasketch.html#autotoc_md7',1,'Setting the Motor Driver Currents']]],
  ['custom_20functions_47',['Custom Functions',['../stepasketch.html#autotoc_md31',1,'']]]
];
