var searchData=
[
  ['a_20install_20arduino_20teensy_20support_0',['A. Install Arduino + Teensy Support',['../getting_started.html#autotoc_md35',1,'']]],
  ['a_20sketch_1',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md59',1,'']]],
  ['a_20sketch_20etch_20a_20sketch_2',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md59',1,'']]],
  ['a_20sketch_20example_3',['Step-A-Sketch Example',['../stepasketch.html',1,'tutorials_docs']]],
  ['add_5fmove_4',['add_move',['../class_time_based_interpolator.html#a8a9726f66bd6e19c1f83ef04493e3f68',1,'TimeBasedInterpolator']]],
  ['add_5ftimed_5fmove_5',['add_timed_move',['../class_time_based_interpolator.html#a8626366c48b37c94725b9a3b8fcffb95',1,'TimeBasedInterpolator']]],
  ['additional_20resources_6',['Additional Resources',['../ssl.html#autotoc_md77',1,'']]],
  ['all_20stepdance_20components_7',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['also_8',['See Also',['../highspeed.html#autotoc_md65',1,'']]],
  ['amplitude_9',['amplitude',['../class_wave_generator1_d.html#a486debcdc8df3736920fa9c6f482351f',1,'WaveGenerator1D::amplitude'],['../class_wave_generator2_d.html#a3da3460a9fe5835b230c4b43308c50be',1,'WaveGenerator2D::amplitude']]],
  ['analog_20digital_20inputs_10',['Encoders and Analog / Digital Inputs',['../hardware.html#autotoc_md43',1,'']]],
  ['analog_20input_20test_11',['&lt;a class=&quot;el&quot; href=&quot;analog_in_test_2analog_in_test_8ino-example.html&quot; title=&quot;analog_in_test/analog_in_test.ino&quot;&gt;Analog Input Test&lt;/a&gt;',['../examples_core.html#autotoc_md96',1,'']]],
  ['analog_5fin_5ftest_20analog_5fin_5ftest_20ino_20analog_20input_20test_12',['&lt;a class=&quot;el&quot; href=&quot;analog_in_test_2analog_in_test_8ino-example.html&quot; title=&quot;analog_in_test/analog_in_test.ino&quot;&gt;Analog Input Test&lt;/a&gt;',['../examples_core.html#autotoc_md96',1,'']]],
  ['analog_5fin_5ftest_20ino_20analog_20input_20test_13',['&lt;a class=&quot;el&quot; href=&quot;analog_in_test_2analog_in_test_8ino-example.html&quot; title=&quot;analog_in_test/analog_in_test.ino&quot;&gt;Analog Input Test&lt;/a&gt;',['../examples_core.html#autotoc_md96',1,'']]],
  ['analoginput_14',['AnalogInput',['../class_analog_input.html',1,'AnalogInput'],['../class_analog_input.html#af40968136e406531f8838434f1c1356b',1,'AnalogInput::AnalogInput()']]],
  ['and_20analog_20digital_20inputs_15',['Encoders and Analog / Digital Inputs',['../hardware.html#autotoc_md43',1,'']]],
  ['and_20control_20knob_20mounting_16',['Display and Control Knob Mounting',['../hardware.html#autotoc_md47',1,'']]],
  ['and_20dependencies_17',['B. Install Libraries and Dependencies',['../getting_started.html#autotoc_md36',1,'']]],
  ['and_20motor_20interfaces_18',['Stepper Drivers and Motor Interfaces',['../hardware.html#autotoc_md42',1,'']]],
  ['and_20playback_19',['Recording and Playback',['../group__recording.html',1,'']]],
  ['and_20select_20the_20board_20',['C. Connect and Select the Board',['../getting_started.html#autotoc_md37',1,'']]],
  ['arduino_20programming_20environment_21',['2. Set Up Arduino Programming Environment',['../getting_started.html#autotoc_md34',1,'']]],
  ['arduino_20teensy_20support_22',['A. Install Arduino + Teensy Support',['../getting_started.html#autotoc_md35',1,'']]],
  ['axidraw_23',['&lt;a class=&quot;el&quot; href=&quot;examples_plotting.html&quot; title=&quot;Plotting &amp;amp; Axidraw&quot;&gt;Plotting &amp;amp; AxiDraw&lt;/a&gt;',['../examples.html#autotoc_md90',1,'']]],
  ['axidraw_24',['Plotting &amp;amp; Axidraw',['../examples_plotting.html',1,'code_examples']]],
  ['axidraw_20ebb_20controller_20emulator_25',['Axidraw &quot;EBB&quot; Controller Emulator',['../hardware.html#autotoc_md60',1,'']]],
  ['axidraw_20ebb_20controller_20emulator_20example_26',['Axidraw EBB Controller Emulator Example',['../ebb.html',1,'tutorials_docs']]],
  ['axidraw_20interface_27',['&lt;a class=&quot;el&quot; href=&quot;axidraw_interface_2axidraw_interface_8ino-example.html&quot; title=&quot;axidraw_interface/axidraw_interface.ino&quot;&gt;AxiDraw Interface&lt;/a&gt;',['../examples_plotting.html#autotoc_md109',1,'']]],
  ['axidraw_20recorder_28',['&lt;a class=&quot;el&quot; href=&quot;axidraw_recorder_2axidraw_recorder_8ino-example.html&quot; title=&quot;axidraw_recorder/axidraw_recorder.ino&quot;&gt;AxiDraw Recorder&lt;/a&gt;',['../examples_plotting.html#autotoc_md110',1,'']]],
  ['axidraw_5finterface_20axidraw_5finterface_20ino_20axidraw_20interface_29',['&lt;a class=&quot;el&quot; href=&quot;axidraw_interface_2axidraw_interface_8ino-example.html&quot; title=&quot;axidraw_interface/axidraw_interface.ino&quot;&gt;AxiDraw Interface&lt;/a&gt;',['../examples_plotting.html#autotoc_md109',1,'']]],
  ['axidraw_5finterface_20ino_20axidraw_20interface_30',['&lt;a class=&quot;el&quot; href=&quot;axidraw_interface_2axidraw_interface_8ino-example.html&quot; title=&quot;axidraw_interface/axidraw_interface.ino&quot;&gt;AxiDraw Interface&lt;/a&gt;',['../examples_plotting.html#autotoc_md109',1,'']]],
  ['axidraw_5frecorder_20axidraw_5frecorder_20ino_20axidraw_20recorder_31',['&lt;a class=&quot;el&quot; href=&quot;axidraw_recorder_2axidraw_recorder_8ino-example.html&quot; title=&quot;axidraw_recorder/axidraw_recorder.ino&quot;&gt;AxiDraw Recorder&lt;/a&gt;',['../examples_plotting.html#autotoc_md110',1,'']]],
  ['axidraw_5frecorder_20ino_20axidraw_20recorder_32',['&lt;a class=&quot;el&quot; href=&quot;axidraw_recorder_2axidraw_recorder_8ino-example.html&quot; title=&quot;axidraw_recorder/axidraw_recorder.ino&quot;&gt;AxiDraw Recorder&lt;/a&gt;',['../examples_plotting.html#autotoc_md110',1,'']]],
  ['axis_20encoded_20step_20pulses_33',['Signals: Axis-Encoded Step Pulses',['../hardware.html#autotoc_md56',1,'']]],
  ['axis_20synchronous_20motion_34',['Frames: Multi-Axis Synchronous Motion',['../hardware.html#autotoc_md57',1,'']]]
];
