var searchData=
[
  ['pages_0',['Pages',['../software_docs.html#autotoc_md82',1,'Pages'],['../hardware_docs.html#autotoc_md83',1,'Pages'],['../tutorials_docs.html#autotoc_md84',1,'Pages']]],
  ['pantograph_1',['&lt;a class=&quot;el&quot; href=&quot;pantograph_2pantograph_8ino-example.html&quot;&gt;Pantograph&lt;/a&gt;',['../examples_motion.html#autotoc_md103',1,'']]],
  ['pantograph_20basic_20module_2',['&lt;a class=&quot;el&quot; href=&quot;pantograph_basic_module_2pantograph_basic_module_8ino-example.html&quot;&gt;Pantograph Basic Module&lt;/a&gt;',['../examples_motion.html#autotoc_md104',1,'']]],
  ['pantograph_20ino_20pantograph_3',['&lt;a class=&quot;el&quot; href=&quot;pantograph_2pantograph_8ino-example.html&quot;&gt;Pantograph&lt;/a&gt;',['../examples_motion.html#autotoc_md103',1,'']]],
  ['pantograph_20pantograph_20ino_20pantograph_4',['&lt;a class=&quot;el&quot; href=&quot;pantograph_2pantograph_8ino-example.html&quot;&gt;Pantograph&lt;/a&gt;',['../examples_motion.html#autotoc_md103',1,'']]],
  ['pantograph_5fbasic_5fmodule_20ino_20pantograph_20basic_20module_5',['&lt;a class=&quot;el&quot; href=&quot;pantograph_basic_module_2pantograph_basic_module_8ino-example.html&quot;&gt;Pantograph Basic Module&lt;/a&gt;',['../examples_motion.html#autotoc_md104',1,'']]],
  ['pantograph_5fbasic_5fmodule_20pantograph_5fbasic_5fmodule_20ino_20pantograph_20basic_20module_6',['&lt;a class=&quot;el&quot; href=&quot;pantograph_basic_module_2pantograph_basic_module_8ino-example.html&quot;&gt;Pantograph Basic Module&lt;/a&gt;',['../examples_motion.html#autotoc_md104',1,'']]],
  ['pathlengthgenerator2d_7',['PathLengthGenerator2D',['../class_path_length_generator2_d.html',1,'']]],
  ['pathlengthgenerator3d_8',['PathLengthGenerator3D',['../class_path_length_generator3_d.html',1,'']]],
  ['pause_9',['pause',['../class_four_track_recorder.html#a67018398eee1d78010a0d11664a18a3c',1,'FourTrackRecorder::pause()'],['../class_four_track_player.html#a5c67380dcbf4d475a1afb14579f67687',1,'FourTrackPlayer::pause()']]],
  ['peak_20motor_20current_10',['Determine the Peak Motor Current',['../stepasketch.html#autotoc_md8',1,'']]],
  ['phase_11',['phase',['../class_wave_generator1_d.html#a1614580ec0ed79cb209117fcd1b1da39',1,'WaveGenerator1D']]],
  ['playback_12',['Recording and Playback',['../group__recording.html',1,'']]],
  ['playback_5factive_13',['playback_active',['../class_four_track_player.html#aff61f74afb6d2ee067a1485fd69b1d19',1,'FourTrackPlayer']]],
  ['plotting_20axidraw_14',['&lt;a class=&quot;el&quot; href=&quot;examples_plotting.html&quot;&gt;Plotting &amp;amp; AxiDraw&lt;/a&gt;',['../examples.html#autotoc_md90',1,'']]],
  ['plotting_20axidraw_15',['Plotting &amp;amp; Axidraw',['../examples_plotting.html',1,'code_examples']]],
  ['polar_20cartesian_203d_20printer_16',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_2polar_cartesian_3dprinter_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md117',1,'']]],
  ['polar_20cartesian_203d_20printer_20with_20extrusion_17',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_extrusion_2polar_cartesian_3dprinter_extrusion_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer with Extrusion&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md118',1,'']]],
  ['polar_20to_20cartesian_18',['&lt;a class=&quot;el&quot; href=&quot;polar_to_cartesian_2polar_to_cartesian_8ino-example.html&quot;&gt;Polar to Cartesian&lt;/a&gt;',['../examples_kinematics.html#autotoc_md121',1,'']]],
  ['polar_5fcartesian_5f3dprinter_20ino_20polar_20cartesian_203d_20printer_19',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_2polar_cartesian_3dprinter_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md117',1,'']]],
  ['polar_5fcartesian_5f3dprinter_20polar_5fcartesian_5f3dprinter_20ino_20polar_20cartesian_203d_20printer_20',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_2polar_cartesian_3dprinter_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md117',1,'']]],
  ['polar_5fcartesian_5f3dprinter_5fextrusion_20ino_20polar_20cartesian_203d_20printer_20with_20extrusion_21',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_extrusion_2polar_cartesian_3dprinter_extrusion_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer with Extrusion&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md118',1,'']]],
  ['polar_5fcartesian_5f3dprinter_5fextrusion_20polar_5fcartesian_5f3dprinter_5fextrusion_20ino_20polar_20cartesian_203d_20printer_20with_20extrusion_22',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_extrusion_2polar_cartesian_3dprinter_extrusion_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer with Extrusion&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md118',1,'']]],
  ['polar_5fto_5fcartesian_20ino_20polar_20to_20cartesian_23',['&lt;a class=&quot;el&quot; href=&quot;polar_to_cartesian_2polar_to_cartesian_8ino-example.html&quot;&gt;Polar to Cartesian&lt;/a&gt;',['../examples_kinematics.html#autotoc_md121',1,'']]],
  ['polar_5fto_5fcartesian_20polar_5fto_5fcartesian_20ino_20polar_20to_20cartesian_24',['&lt;a class=&quot;el&quot; href=&quot;polar_to_cartesian_2polar_to_cartesian_8ino-example.html&quot;&gt;Polar to Cartesian&lt;/a&gt;',['../examples_kinematics.html#autotoc_md121',1,'']]],
  ['port_20test_25',['&lt;a class=&quot;el&quot; href=&quot;io_port_test_2io_port_test_8ino-example.html&quot;&gt;I/O Port Test&lt;/a&gt;',['../examples_core.html#autotoc_md98',1,'']]],
  ['ports_26',['Ports',['../stepasketch.html#autotoc_md23',1,'Configure Output Ports'],['../hardware.html#autotoc_md46',1,'Stepdance Ports'],['../hardware.html#autotoc_md54',1,'Stepdance Ports']]],
  ['position_27',['position',['../struct_time_based_interpolator_1_1position.html',1,'TimeBasedInterpolator']]],
  ['position_20generator_28',['Configure Position Generator',['../stepasketch.html#autotoc_md28',1,'']]],
  ['positiongenerator_29',['PositionGenerator',['../class_position_generator.html',1,'PositionGenerator'],['../class_position_generator.html#a1a1837f8127c065959382a5754ab1a53',1,'PositionGenerator::PositionGenerator()'],['../stepasketch.html#autotoc_md20',1,'PositionGenerator']]],
  ['power_20inputs_30',['DC Power Inputs',['../hardware.html#autotoc_md45',1,'']]],
  ['printer_31',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_2polar_cartesian_3dprinter_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md117',1,'']]],
  ['printer_20texturizer_32',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_2clay_3dprinter_texturizer_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md115',1,'']]],
  ['printer_20texturizer_20modularized_20v2_33',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_modularized_v2_2clay_3dprinter_texturizer_modularized_v2_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer Modularized V2&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md116',1,'']]],
  ['printer_20variants_34',['Printer Variants',['../examples.html#autotoc_md91',1,'<a class="el" href="examples_clayprinter.html">Clay 3D Printer Variants</a>'],['../examples_clayprinter.html',1,'Clay 3D Printer Variants']]],
  ['printer_20with_20extrusion_35',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_extrusion_2polar_cartesian_3dprinter_extrusion_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer with Extrusion&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md118',1,'']]],
  ['procedure_20call_36',['Procedure Call',['../examples_core.html#autotoc_md100',1,'<a class="el" href="remote_procedure_call_2remote_procedure_call_8ino-example.html">Remote Procedure Call</a>'],['../group__rpc.html',1,'Remote Procedure Call']]],
  ['programming_20environment_37',['2. Set Up Arduino Programming Environment',['../getting_started.html#autotoc_md34',1,'']]],
  ['pulses_38',['Signals: Axis-Encoded Step Pulses',['../hardware.html#autotoc_md56',1,'']]]
];
