var searchData=
[
  ['c_20connect_20and_20select_20the_20board_0',['C. Connect and Select the Board',['../getting_started.html#autotoc_md37',1,'']]],
  ['calculate_20the_20reference_20voltage_1',['Calculate the Reference Voltage',['../stepasketch.html#autotoc_md9',1,'']]],
  ['channel_2',['Channel',['../class_channel.html',1,'Channel'],['../stepasketch.html#autotoc_md16',1,'Channel']]],
  ['channels_3',['Channels',['../group__channels.html',1,'Channels'],['../stepasketch.html#autotoc_md24',1,'Configure Channels']]],
  ['circlegenerator_4',['CircleGenerator',['../class_circle_generator.html',1,'']]],
  ['clear_5finvert_5',['clear_invert',['../class_button.html#abc0a668359f51eb1453ea759d8bb3525',1,'Button']]],
  ['clearlowerthreshold_6',['clearLowerThreshold',['../class_threshold_generator.html#a5138b879ac51822745611494315558d8',1,'ThresholdGenerator']]],
  ['clearupperthreshold_7',['clearUpperThreshold',['../class_threshold_generator.html#a7dbe3c7ac94b27e206f4d198b130129f',1,'ThresholdGenerator']]],
  ['code_8',['Code',['../stepasketch.html#autotoc_md11',1,'']]],
  ['components_9',['Core Components',['../group__core.html',1,'']]],
  ['components_10',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['concepts_11',['Concepts',['../highspeed.html#autotoc_md62',1,'']]],
  ['configuration_12',['Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md61',1,'High-Speed Frame Configuration']]],
  ['configure_20channels_13',['Configure Channels',['../stepasketch.html#autotoc_md24',1,'']]],
  ['configure_20encoders_14',['Configure Encoders',['../stepasketch.html#autotoc_md25',1,'']]],
  ['configure_20output_20ports_15',['Configure Output Ports',['../stepasketch.html#autotoc_md23',1,'']]],
  ['configure_20position_20generator_16',['Configure Position Generator',['../stepasketch.html#autotoc_md28',1,'']]],
  ['configure_20the_20button_17',['Configure the Button',['../stepasketch.html#autotoc_md27',1,'']]],
  ['configure_20the_20kinematics_18',['Configure the Kinematics',['../stepasketch.html#autotoc_md26',1,'']]],
  ['configuring_20the_20stepdance_20driver_20board_19',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['connect_20and_20select_20the_20board_20',['C. Connect and Select the Board',['../getting_started.html#autotoc_md37',1,'']]],
  ['connector_21',['Connector',['../taiss.html#autotoc_md80',1,'']]],
  ['connectors_22',['QWIIC Connectors',['../hardware.html#autotoc_md44',1,'']]],
  ['considerations_23',['Considerations',['../highspeed.html#autotoc_md63',1,'']]],
  ['control_20knob_20mounting_24',['Display and Control Knob Mounting',['../hardware.html#autotoc_md47',1,'']]],
  ['controller_20emulator_25',['Axidraw &quot;EBB&quot; Controller Emulator',['../hardware.html#autotoc_md60',1,'']]],
  ['controller_20emulator_20example_26',['Axidraw EBB Controller Emulator Example',['../ebb.html',1,'']]],
  ['core_20components_27',['Core Components',['../group__core.html',1,'']]],
  ['current_28',['Determine the Peak Motor Current',['../stepasketch.html#autotoc_md8',1,'']]],
  ['current_5fposition_29',['current_position',['../class_channel.html#a3c96c0b9aee1a6e7d9bb265ccb9c86e7',1,'Channel']]],
  ['currents_30',['Setting the Motor Driver Currents',['../stepasketch.html#autotoc_md7',1,'']]],
  ['custom_20functions_31',['Custom Functions',['../stepasketch.html#autotoc_md31',1,'']]]
];
