var searchData=
[
  ['calculate_20the_20reference_20voltage_0',['Calculate the Reference Voltage',['../stepasketch.html#autotoc_md9',1,'']]],
  ['channel_1',['Channel',['../class_channel.html',1,'Channel'],['../stepasketch.html#autotoc_md16',1,'Channel']]],
  ['channels_2',['Channels',['../group__channels.html',1,'Channels'],['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/SSL/readme.md#autotoc_md63',1,'Channels'],['../stepasketch.html#autotoc_md24',1,'Configure Channels']]],
  ['circlegenerator_3',['CircleGenerator',['../class_circle_generator.html',1,'']]],
  ['clear_5finvert_4',['clear_invert',['../class_button.html#abc0a668359f51eb1453ea759d8bb3525',1,'Button']]],
  ['code_5',['Code',['../stepasketch.html#autotoc_md11',1,'']]],
  ['components_6',['Core Components',['../group__core.html',1,'']]],
  ['components_7',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['concepts_8',['Concepts',['../highspeed.html#autotoc_md33',1,'']]],
  ['configuration_9',['Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md32',1,'High-Speed Frame Configuration']]],
  ['configure_20channels_10',['Configure Channels',['../stepasketch.html#autotoc_md24',1,'']]],
  ['configure_20encoders_11',['Configure Encoders',['../stepasketch.html#autotoc_md25',1,'']]],
  ['configure_20output_20ports_12',['Configure Output Ports',['../stepasketch.html#autotoc_md23',1,'']]],
  ['configure_20position_20generator_13',['Configure Position Generator',['../stepasketch.html#autotoc_md28',1,'']]],
  ['configure_20the_20button_14',['Configure the Button',['../stepasketch.html#autotoc_md27',1,'']]],
  ['configure_20the_20kinematics_15',['Configure the Kinematics',['../stepasketch.html#autotoc_md26',1,'']]],
  ['configuring_20the_20stepdance_20driver_20board_16',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['connector_17',['Connector',['../taiss.html#autotoc_md68',1,'']]],
  ['connectors_18',['QWIIC Connectors',['../index.html#autotoc_md43',1,'']]],
  ['considerations_19',['Considerations',['../highspeed.html#autotoc_md34',1,'']]],
  ['control_20knob_20mounting_20',['Display and Control Knob Mounting',['../index.html#autotoc_md46',1,'']]],
  ['controller_20emulator_21',['Axidraw &quot;EBB&quot; Controller Emulator',['../index.html#autotoc_md59',1,'']]],
  ['controller_20emulator_20example_22',['Axidraw EBB Controller Emulator Example',['../ebb.html',1,'']]],
  ['core_20components_23',['Core Components',['../group__core.html',1,'']]],
  ['current_24',['Determine the Peak Motor Current',['../stepasketch.html#autotoc_md8',1,'']]],
  ['current_5fposition_25',['current_position',['../class_channel.html#a3c96c0b9aee1a6e7d9bb265ccb9c86e7',1,'Channel']]],
  ['currents_26',['Setting the Motor Driver Currents',['../stepasketch.html#autotoc_md7',1,'']]],
  ['custom_20functions_27',['Custom Functions',['../stepasketch.html#autotoc_md31',1,'']]]
];
