var searchData=
[
  ['see_20also_0',['See Also',['../highspeed.html#autotoc_md65',1,'']]],
  ['select_20the_20board_1',['C. Connect and Select the Board',['../getting_started.html#autotoc_md37',1,'']]],
  ['serial_20monitor_2',['D. Test Serial Monitor',['../getting_started.html#autotoc_md38',1,'']]],
  ['servo_20driver_3',['Hobby Servo Driver',['../hardware.html#autotoc_md53',1,'']]],
  ['servo_20motor_4',['Wiring the Servo Motor',['../stepasketch.html#autotoc_md5',1,'']]],
  ['set_20motor_20currents_5',['&lt;a class=&quot;el&quot; href=&quot;set_motor_currents_2set_motor_currents_8ino-example.html&quot;&gt;Set Motor Currents&lt;/a&gt;',['../examples_core.html#autotoc_md99',1,'']]],
  ['set_20the_20reference_20voltage_6',['Set the Reference Voltage',['../stepasketch.html#autotoc_md10',1,'']]],
  ['set_20up_20arduino_20programming_20environment_7',['2. Set Up Arduino Programming Environment',['../getting_started.html#autotoc_md34',1,'']]],
  ['set_20up_20your_20hardware_8',['1. Set Up Your Hardware',['../getting_started.html#autotoc_md33',1,'']]],
  ['set_5fmotor_5fcurrents_20ino_20set_20motor_20currents_9',['&lt;a class=&quot;el&quot; href=&quot;set_motor_currents_2set_motor_currents_8ino-example.html&quot;&gt;Set Motor Currents&lt;/a&gt;',['../examples_core.html#autotoc_md99',1,'']]],
  ['set_5fmotor_5fcurrents_20set_5fmotor_5fcurrents_20ino_20set_20motor_20currents_10',['&lt;a class=&quot;el&quot; href=&quot;set_motor_currents_2set_motor_currents_8ino-example.html&quot;&gt;Set Motor Currents&lt;/a&gt;',['../examples_core.html#autotoc_md99',1,'']]],
  ['setting_20the_20motor_20driver_20currents_11',['Setting the Motor Driver Currents',['../stepasketch.html#autotoc_md7',1,'']]],
  ['setup_12',['Setup()',['../stepasketch.html#autotoc_md21',1,'']]],
  ['signals_3a_20axis_20encoded_20step_20pulses_13',['Signals: Axis-Encoded Step Pulses',['../hardware.html#autotoc_md56',1,'']]],
  ['sketch_14',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md59',1,'']]],
  ['sketch_20etch_20a_20sketch_15',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md59',1,'']]],
  ['sketch_20example_16',['Step-A-Sketch Example',['../stepasketch.html',1,'tutorials_docs']]],
  ['sketch_20extrude_17',['&lt;a class=&quot;el&quot; href=&quot;ender_sketch_extrude_2ender_sketch_extrude_8ino-example.html&quot;&gt;Ender Sketch Extrude&lt;/a&gt;',['../examples_legacy.html#autotoc_md124',1,'']]],
  ['sketches_18',['Core Example Sketches',['../examples_core.html',1,'code_examples']]],
  ['software_20documentation_19',['Software Documentation',['../software_docs.html',1,'documentation']]],
  ['software_20library_20documentation_20',['Stepdance Software Library Documentation',['../ssl.html',1,'software_docs']]],
  ['software_20library_20ssl_20documentation_21',['Stepdance Software Library (SSL) Documentation',['../index.html#autotoc_md70',1,'']]],
  ['speed_20frame_20configuration_22',['Speed Frame Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md61',1,'High-Speed Frame Configuration']]],
  ['ssl_20documentation_23',['Stepdance Software Library (SSL) Documentation',['../index.html#autotoc_md70',1,'']]],
  ['start_20stepdance_24',['Start Stepdance',['../stepasketch.html#autotoc_md29',1,'']]],
  ['started_25',['Started',['../index.html#autotoc_md68',1,'Getting Started'],['../ssl.html#autotoc_md73',1,'Getting Started']]],
  ['started_20with_20stepdance_26',['Getting Started with Stepdance',['../getting_started.html',1,'tutorials_docs']]],
  ['step_20a_20sketch_20etch_20a_20sketch_27',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md59',1,'']]],
  ['step_20a_20sketch_20example_28',['Step-A-Sketch Example',['../stepasketch.html',1,'tutorials_docs']]],
  ['step_20pulses_29',['Signals: Axis-Encoded Step Pulses',['../hardware.html#autotoc_md56',1,'']]],
  ['stepasketch_30',['&lt;a class=&quot;el&quot; href=&quot;gcode_stepasketch_2gcode_stepasketch_8ino-example.html&quot;&gt;G-Code Stepasketch&lt;/a&gt;',['../examples_plotting.html#autotoc_md110',1,'']]],
  ['stepasketch_20old_31',['&lt;a class=&quot;el&quot; href=&quot;stepasketch_old_2stepasketch_old_8ino-example.html&quot;&gt;Stepasketch Old&lt;/a&gt;',['../examples_legacy.html#autotoc_md123',1,'']]],
  ['stepasketch_20with_20inputs_32',['&lt;a class=&quot;el&quot; href=&quot;stepasketch_with_inputs_2stepasketch_with_inputs_8ino-example.html&quot;&gt;Stepasketch with Inputs&lt;/a&gt;',['../examples_plotting.html#autotoc_md111',1,'']]],
  ['stepasketch_5fold_20ino_20stepasketch_20old_33',['&lt;a class=&quot;el&quot; href=&quot;stepasketch_old_2stepasketch_old_8ino-example.html&quot;&gt;Stepasketch Old&lt;/a&gt;',['../examples_legacy.html#autotoc_md123',1,'']]],
  ['stepasketch_5fold_20stepasketch_5fold_20ino_20stepasketch_20old_34',['&lt;a class=&quot;el&quot; href=&quot;stepasketch_old_2stepasketch_old_8ino-example.html&quot;&gt;Stepasketch Old&lt;/a&gt;',['../examples_legacy.html#autotoc_md123',1,'']]],
  ['stepasketch_5fwith_5finputs_20ino_20stepasketch_20with_20inputs_35',['&lt;a class=&quot;el&quot; href=&quot;stepasketch_with_inputs_2stepasketch_with_inputs_8ino-example.html&quot;&gt;Stepasketch with Inputs&lt;/a&gt;',['../examples_plotting.html#autotoc_md111',1,'']]],
  ['stepasketch_5fwith_5finputs_20stepasketch_5fwith_5finputs_20ino_20stepasketch_20with_20inputs_36',['&lt;a class=&quot;el&quot; href=&quot;stepasketch_with_inputs_2stepasketch_with_inputs_8ino-example.html&quot;&gt;Stepasketch with Inputs&lt;/a&gt;',['../examples_plotting.html#autotoc_md111',1,'']]],
  ['stepdance_37',['Stepdance',['../getting_started.html',1,'Getting Started with Stepdance'],['../stepasketch.html#autotoc_md29',1,'Start Stepdance'],['../index.html#autotoc_md67',1,'What is Stepdance?']]],
  ['stepdance_20components_38',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['stepdance_20driver_20board_39',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['stepdance_20example_20index_40',['Stepdance Example Index',['../examples.html',1,'code_examples']]],
  ['stepdance_20hardware_41',['Stepdance Hardware',['../hardware.html#autotoc_md40',1,'']]],
  ['stepdance_20hardware_20documentation_42',['Stepdance Hardware Documentation',['../hardware.html',1,'hardware_docs']]],
  ['stepdance_20overview_43',['Stepdance Overview',['../index.html',1,'']]],
  ['stepdance_20ports_44',['Stepdance Ports',['../hardware.html#autotoc_md46',1,'Stepdance Ports'],['../hardware.html#autotoc_md54',1,'Stepdance Ports']]],
  ['stepdance_20software_20library_20documentation_45',['Stepdance Software Library Documentation',['../ssl.html',1,'software_docs']]],
  ['stepdance_20software_20library_20ssl_20documentation_46',['Stepdance Software Library (SSL) Documentation',['../index.html#autotoc_md70',1,'']]],
  ['stepper_20drivers_20and_20motor_20interfaces_47',['Stepper Drivers and Motor Interfaces',['../hardware.html#autotoc_md42',1,'']]],
  ['stepper_20motors_48',['Stepper Motors',['../stepasketch.html#autotoc_md22',1,'Enable the Stepper Motors'],['../stepasketch.html#autotoc_md4',1,'Wiring Stepper Motors']]],
  ['steps_49',['3. Next Steps',['../getting_started.html#autotoc_md39',1,'']]],
  ['support_50',['A. Install Arduino + Teensy Support',['../getting_started.html#autotoc_md35',1,'']]],
  ['supported_20hardware_51',['Supported Hardware',['../ssl.html#autotoc_md76',1,'']]],
  ['synchronous_20motion_52',['Frames: Multi-Axis Synchronous Motion',['../hardware.html#autotoc_md57',1,'']]]
];
