var searchData=
[
  ['i_20o_20port_20test_0',['&lt;a class=&quot;el&quot; href=&quot;io_port_test_2io_port_test_8ino-example.html&quot;&gt;I/O Port Test&lt;/a&gt;',['../examples_core.html#autotoc_md98',1,'']]],
  ['includes_1',['Includes',['../stepasketch.html#autotoc_md13',1,'']]],
  ['index_2',['Stepdance Example Index',['../examples.html',1,'code_examples']]],
  ['ino_20analog_20input_20test_3',['&lt;a class=&quot;el&quot; href=&quot;analog_in_test_2analog_in_test_8ino-example.html&quot;&gt;Analog Input Test&lt;/a&gt;',['../examples_core.html#autotoc_md96',1,'']]],
  ['ino_20axidraw_20interface_4',['&lt;a class=&quot;el&quot; href=&quot;axidraw_interface_2axidraw_interface_8ino-example.html&quot;&gt;AxiDraw Interface&lt;/a&gt;',['../examples_plotting.html#autotoc_md108',1,'']]],
  ['ino_20axidraw_20recorder_5',['&lt;a class=&quot;el&quot; href=&quot;axidraw_recorder_2axidraw_recorder_8ino-example.html&quot;&gt;AxiDraw Recorder&lt;/a&gt;',['../examples_plotting.html#autotoc_md109',1,'']]],
  ['ino_20clay_203d_20printer_20texturizer_6',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_2clay_3dprinter_texturizer_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md114',1,'']]],
  ['ino_20clay_203d_20printer_20texturizer_20modularized_20v2_7',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_modularized_v2_2clay_3dprinter_texturizer_modularized_v2_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer Modularized V2&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md115',1,'']]],
  ['ino_20encoder_20test_8',['&lt;a class=&quot;el&quot; href=&quot;encoder_test_2encoder_test_8ino-example.html&quot;&gt;Encoder Test&lt;/a&gt;',['../examples_core.html#autotoc_md97',1,'']]],
  ['ino_20ender_20sketch_20extrude_9',['&lt;a class=&quot;el&quot; href=&quot;ender_sketch_extrude_2ender_sketch_extrude_8ino-example.html&quot;&gt;Ender Sketch Extrude&lt;/a&gt;',['../examples_legacy.html#autotoc_md124',1,'']]],
  ['ino_20g_20code_20stepasketch_10',['&lt;a class=&quot;el&quot; href=&quot;gcode_stepasketch_2gcode_stepasketch_8ino-example.html&quot;&gt;G-Code Stepasketch&lt;/a&gt;',['../examples_plotting.html#autotoc_md110',1,'']]],
  ['ino_20harmonograph_20basic_20module_11',['&lt;a class=&quot;el&quot; href=&quot;harmonograph_basic_module_2harmonograph_basic_module_8ino-example.html&quot;&gt;Harmonograph Basic Module&lt;/a&gt;',['../examples_motion.html#autotoc_md104',1,'']]],
  ['ino_20i_20o_20port_20test_12',['&lt;a class=&quot;el&quot; href=&quot;io_port_test_2io_port_test_8ino-example.html&quot;&gt;I/O Port Test&lt;/a&gt;',['../examples_core.html#autotoc_md98',1,'']]],
  ['ino_20pantograph_13',['&lt;a class=&quot;el&quot; href=&quot;pantograph_2pantograph_8ino-example.html&quot;&gt;Pantograph&lt;/a&gt;',['../examples_motion.html#autotoc_md102',1,'']]],
  ['ino_20pantograph_20basic_20module_14',['&lt;a class=&quot;el&quot; href=&quot;pantograph_basic_module_2pantograph_basic_module_8ino-example.html&quot;&gt;Pantograph Basic Module&lt;/a&gt;',['../examples_motion.html#autotoc_md103',1,'']]],
  ['ino_20polar_20cartesian_203d_20printer_15',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_2polar_cartesian_3dprinter_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md116',1,'']]],
  ['ino_20polar_20cartesian_203d_20printer_20with_20extrusion_16',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_extrusion_2polar_cartesian_3dprinter_extrusion_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer with Extrusion&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md117',1,'']]],
  ['ino_20polar_20to_20cartesian_17',['&lt;a class=&quot;el&quot; href=&quot;polar_to_cartesian_2polar_to_cartesian_8ino-example.html&quot;&gt;Polar to Cartesian&lt;/a&gt;',['../examples_kinematics.html#autotoc_md120',1,'']]],
  ['ino_20set_20motor_20currents_18',['&lt;a class=&quot;el&quot; href=&quot;set_motor_currents_2set_motor_currents_8ino-example.html&quot;&gt;Set Motor Currents&lt;/a&gt;',['../examples_core.html#autotoc_md99',1,'']]],
  ['ino_20stepasketch_20old_19',['&lt;a class=&quot;el&quot; href=&quot;stepasketch_old_2stepasketch_old_8ino-example.html&quot;&gt;Stepasketch Old&lt;/a&gt;',['../examples_legacy.html#autotoc_md123',1,'']]],
  ['ino_20stepasketch_20with_20inputs_20',['&lt;a class=&quot;el&quot; href=&quot;stepasketch_with_inputs_2stepasketch_with_inputs_8ino-example.html&quot;&gt;Stepasketch with Inputs&lt;/a&gt;',['../examples_plotting.html#autotoc_md111',1,'']]],
  ['ino_20wheelbot_21',['&lt;a class=&quot;el&quot; href=&quot;wheelbot_2wheelbot_8ino-example.html&quot;&gt;Wheelbot&lt;/a&gt;',['../examples_motion.html#autotoc_md105',1,'']]],
  ['input_20test_22',['&lt;a class=&quot;el&quot; href=&quot;analog_in_test_2analog_in_test_8ino-example.html&quot;&gt;Analog Input Test&lt;/a&gt;',['../examples_core.html#autotoc_md96',1,'']]],
  ['inputs_23',['Inputs',['../examples_plotting.html#autotoc_md111',1,'<a class="el" href="stepasketch_with_inputs_2stepasketch_with_inputs_8ino-example.html">Stepasketch with Inputs</a>'],['../hardware.html#autotoc_md45',1,'DC Power Inputs'],['../hardware.html#autotoc_md43',1,'Encoders and Analog / Digital Inputs']]],
  ['install_20arduino_20teensy_20support_24',['A. Install Arduino + Teensy Support',['../getting_started.html#autotoc_md35',1,'']]],
  ['install_20libraries_20and_20dependencies_25',['B. Install Libraries and Dependencies',['../getting_started.html#autotoc_md36',1,'']]],
  ['interface_26',['&lt;a class=&quot;el&quot; href=&quot;axidraw_interface_2axidraw_interface_8ino-example.html&quot;&gt;AxiDraw Interface&lt;/a&gt;',['../examples_plotting.html#autotoc_md108',1,'']]],
  ['interfaces_27',['Stepper Drivers and Motor Interfaces',['../hardware.html#autotoc_md42',1,'']]],
  ['introduction_28',['Introduction',['../ssl.html#autotoc_md71',1,'']]],
  ['io_5fport_5ftest_20ino_20i_20o_20port_20test_29',['&lt;a class=&quot;el&quot; href=&quot;io_port_test_2io_port_test_8ino-example.html&quot;&gt;I/O Port Test&lt;/a&gt;',['../examples_core.html#autotoc_md98',1,'']]],
  ['io_5fport_5ftest_20io_5fport_5ftest_20ino_20i_20o_20port_20test_30',['&lt;a class=&quot;el&quot; href=&quot;io_port_test_2io_port_test_8ino-example.html&quot;&gt;I/O Port Test&lt;/a&gt;',['../examples_core.html#autotoc_md98',1,'']]],
  ['is_20stepdance_31',['What is Stepdance?',['../index.html#autotoc_md67',1,'']]]
];
