var searchData=
[
  ['c_20connect_20and_20select_20the_20board_0',['C. Connect and Select the Board',['../getting_started.html#autotoc_md37',1,'']]],
  ['calculate_20the_20reference_20voltage_1',['Calculate the Reference Voltage',['../stepasketch.html#autotoc_md9',1,'']]],
  ['cartesian_2',['&lt;a class=&quot;el&quot; href=&quot;polar_to_cartesian_2polar_to_cartesian_8ino-example.html&quot;&gt;Polar to Cartesian&lt;/a&gt;',['../examples_kinematics.html#autotoc_md120',1,'']]],
  ['cartesian_203d_20printer_3',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_2polar_cartesian_3dprinter_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md116',1,'']]],
  ['cartesian_203d_20printer_20with_20extrusion_4',['&lt;a class=&quot;el&quot; href=&quot;polar_cartesian_3dprinter_extrusion_2polar_cartesian_3dprinter_extrusion_8ino-example.html&quot;&gt;Polar Cartesian 3D Printer with Extrusion&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md117',1,'']]],
  ['categories_5',['Categories',['../documentation.html#autotoc_md81',1,'Categories'],['../examples.html#autotoc_md87',1,'Categories'],['../code_examples.html#autotoc_md86',1,'Example Categories']]],
  ['channel_6',['Channel',['../stepasketch.html#autotoc_md16',1,'']]],
  ['channels_7',['Configure Channels',['../stepasketch.html#autotoc_md24',1,'']]],
  ['clay_203d_20printer_20texturizer_8',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_2clay_3dprinter_texturizer_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md114',1,'']]],
  ['clay_203d_20printer_20texturizer_20modularized_20v2_9',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_modularized_v2_2clay_3dprinter_texturizer_modularized_v2_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer Modularized V2&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md115',1,'']]],
  ['clay_203d_20printer_20variants_10',['Clay 3D Printer Variants',['../examples.html#autotoc_md91',1,'<a class="el" href="examples_clayprinter.html">Clay 3D Printer Variants</a>'],['../examples_clayprinter.html',1,'Clay 3D Printer Variants']]],
  ['clay_5f3dprinter_5ftexturizer_20clay_5f3dprinter_5ftexturizer_20ino_20clay_203d_20printer_20texturizer_11',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_2clay_3dprinter_texturizer_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md114',1,'']]],
  ['clay_5f3dprinter_5ftexturizer_20ino_20clay_203d_20printer_20texturizer_12',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_2clay_3dprinter_texturizer_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md114',1,'']]],
  ['clay_5f3dprinter_5ftexturizer_5fmodularized_5fv2_20clay_5f3dprinter_5ftexturizer_5fmodularized_5fv2_20ino_20clay_203d_20printer_20texturizer_20modularized_20v2_13',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_modularized_v2_2clay_3dprinter_texturizer_modularized_v2_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer Modularized V2&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md115',1,'']]],
  ['clay_5f3dprinter_5ftexturizer_5fmodularized_5fv2_20ino_20clay_203d_20printer_20texturizer_20modularized_20v2_14',['&lt;a class=&quot;el&quot; href=&quot;clay_3dprinter_texturizer_modularized_v2_2clay_3dprinter_texturizer_modularized_v2_8ino-example.html&quot;&gt;Clay 3D Printer Texturizer Modularized V2&lt;/a&gt;',['../examples_clayprinter.html#autotoc_md115',1,'']]],
  ['code_15',['Code',['../stepasketch.html#autotoc_md11',1,'']]],
  ['code_20examples_16',['Code Examples',['../code_examples.html',1,'documentation']]],
  ['code_20stepasketch_17',['&lt;a class=&quot;el&quot; href=&quot;gcode_stepasketch_2gcode_stepasketch_8ino-example.html&quot;&gt;G-Code Stepasketch&lt;/a&gt;',['../examples_plotting.html#autotoc_md110',1,'']]],
  ['components_18',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['concepts_19',['Concepts',['../examples.html#autotoc_md88',1,'<a class="el" href="examples_core.html">Core Concepts</a>'],['../highspeed.html#autotoc_md62',1,'Concepts']]],
  ['configuration_20',['Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md61',1,'High-Speed Frame Configuration']]],
  ['configure_20channels_21',['Configure Channels',['../stepasketch.html#autotoc_md24',1,'']]],
  ['configure_20encoders_22',['Configure Encoders',['../stepasketch.html#autotoc_md25',1,'']]],
  ['configure_20output_20ports_23',['Configure Output Ports',['../stepasketch.html#autotoc_md23',1,'']]],
  ['configure_20position_20generator_24',['Configure Position Generator',['../stepasketch.html#autotoc_md28',1,'']]],
  ['configure_20the_20button_25',['Configure the Button',['../stepasketch.html#autotoc_md27',1,'']]],
  ['configure_20the_20kinematics_26',['Configure the Kinematics',['../stepasketch.html#autotoc_md26',1,'']]],
  ['configuring_20the_20stepdance_20driver_20board_27',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['connect_20and_20select_20the_20board_28',['C. Connect and Select the Board',['../getting_started.html#autotoc_md37',1,'']]],
  ['connector_29',['Connector',['../taiss.html#autotoc_md80',1,'']]],
  ['connectors_30',['QWIIC Connectors',['../hardware.html#autotoc_md44',1,'']]],
  ['considerations_31',['Considerations',['../highspeed.html#autotoc_md63',1,'']]],
  ['control_20knob_20mounting_32',['Display and Control Knob Mounting',['../hardware.html#autotoc_md47',1,'']]],
  ['controller_20emulator_33',['Axidraw &quot;EBB&quot; Controller Emulator',['../hardware.html#autotoc_md60',1,'']]],
  ['controller_20emulator_20example_34',['Axidraw EBB Controller Emulator Example',['../ebb.html',1,'tutorials_docs']]],
  ['coordinate_20transforms_35',['Coordinate Transforms',['../examples.html#autotoc_md92',1,'<a class="el" href="examples_kinematics.html">Kinematics / Coordinate Transforms</a>'],['../examples_kinematics.html',1,'Kinematics / Coordinate Transforms']]],
  ['core_20concepts_36',['&lt;a class=&quot;el&quot; href=&quot;examples_core.html&quot;&gt;Core Concepts&lt;/a&gt;',['../examples.html#autotoc_md88',1,'']]],
  ['core_20example_20sketches_37',['Core Example Sketches',['../examples_core.html',1,'code_examples']]],
  ['current_38',['Determine the Peak Motor Current',['../stepasketch.html#autotoc_md8',1,'']]],
  ['currents_39',['Currents',['../examples_core.html#autotoc_md99',1,'<a class="el" href="set_motor_currents_2set_motor_currents_8ino-example.html">Set Motor Currents</a>'],['../stepasketch.html#autotoc_md7',1,'Setting the Motor Driver Currents']]],
  ['custom_20functions_40',['Custom Functions',['../stepasketch.html#autotoc_md31',1,'']]]
];
