var searchData=
[
  ['dc_20power_20inputs_0',['DC Power Inputs',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md38',1,'DC Power Inputs'],['../md_doc_2readme__original.html#autotoc_md69',1,'DC Power Inputs']]],
  ['define_20all_20stepdance_20components_1',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['definition_2',['Board Definition',['../stepasketch.html#autotoc_md12',1,'']]],
  ['determine_20the_20peak_20motor_20current_3',['Determine the Peak Motor Current',['../stepasketch.html#autotoc_md8',1,'']]],
  ['digital_20inputs_4',['Digital Inputs',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md36',1,'Encoders and Analog / Digital Inputs'],['../md_doc_2readme__original.html#autotoc_md67',1,'Encoders and Analog / Digital Inputs']]],
  ['dimensions_5',['Dimensions',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md42',1,'Dimensions'],['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md45',1,'Dimensions'],['../md_doc_2readme__original.html#autotoc_md73',1,'Dimensions'],['../md_doc_2readme__original.html#autotoc_md76',1,'Dimensions']]],
  ['display_20and_20control_20knob_20mounting_6',['Display and Control Knob Mounting',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md40',1,'Display and Control Knob Mounting'],['../md_doc_2readme__original.html#autotoc_md71',1,'Display and Control Knob Mounting']]],
  ['documentation_7',['Documentation',['../index.html#autotoc_md61',1,'Hardware Documentation'],['../md_doc_2readme__original.html',1,'Stepdance Documentation'],['../index.html',1,'Stepdance Documentation'],['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md32',1,'Stepdance Hardware Documentation'],['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/SSL/readme.md#autotoc_md85',1,'Stepdance Software Library Documentation']]],
  ['driver_8',['Driver',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md46',1,'Hobby Servo Driver'],['../md_doc_2readme__original.html#autotoc_md77',1,'Hobby Servo Driver']]],
  ['driver_20board_9',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['driver_20currents_10',['Setting the Motor Driver Currents',['../stepasketch.html#autotoc_md7',1,'']]],
  ['driver_20module_20board_20v1_200_11',['Driver Module Board v1 0',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md34',1,'Driver Module Board v1.0'],['../md_doc_2readme__original.html#autotoc_md65',1,'Driver Module Board v1.0']]],
  ['drivers_20and_20motor_20interfaces_12',['Drivers and Motor Interfaces',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md35',1,'Stepper Drivers and Motor Interfaces'],['../md_doc_2readme__original.html#autotoc_md66',1,'Stepper Drivers and Motor Interfaces']]]
];
