var searchData=
[
  ['see_20also_0',['See Also',['../highspeed.html#autotoc_md65',1,'']]],
  ['select_20the_20board_1',['C. Connect and Select the Board',['../getting_started.html#autotoc_md37',1,'']]],
  ['serial_20monitor_2',['D. Test Serial Monitor',['../getting_started.html#autotoc_md38',1,'']]],
  ['servo_20driver_3',['Hobby Servo Driver',['../hardware.html#autotoc_md53',1,'']]],
  ['servo_20motor_4',['Wiring the Servo Motor',['../stepasketch.html#autotoc_md5',1,'']]],
  ['set_20the_20reference_20voltage_5',['Set the Reference Voltage',['../stepasketch.html#autotoc_md10',1,'']]],
  ['set_20up_20arduino_20programming_20environment_6',['2. Set Up Arduino Programming Environment',['../getting_started.html#autotoc_md34',1,'']]],
  ['set_20up_20your_20hardware_7',['1. Set Up Your Hardware',['../getting_started.html#autotoc_md33',1,'']]],
  ['setting_20the_20motor_20driver_20currents_8',['Setting the Motor Driver Currents',['../stepasketch.html#autotoc_md7',1,'']]],
  ['setup_9',['Setup()',['../stepasketch.html#autotoc_md21',1,'']]],
  ['signals_3a_20axis_20encoded_20step_20pulses_10',['Signals: Axis-Encoded Step Pulses',['../hardware.html#autotoc_md56',1,'']]],
  ['sketch_11',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md59',1,'']]],
  ['sketch_20etch_20a_20sketch_12',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md59',1,'']]],
  ['sketch_20example_13',['Step-A-Sketch Example',['../stepasketch.html',1,'']]],
  ['software_20library_20documentation_14',['Stepdance Software Library Documentation',['../ssl.html',1,'']]],
  ['software_20library_20ssl_20documentation_15',['Stepdance Software Library (SSL) Documentation',['../index.html#autotoc_md70',1,'']]],
  ['speed_20frame_20configuration_16',['Speed Frame Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md61',1,'High-Speed Frame Configuration']]],
  ['ssl_20documentation_17',['Stepdance Software Library (SSL) Documentation',['../index.html#autotoc_md70',1,'']]],
  ['start_20stepdance_18',['Start Stepdance',['../stepasketch.html#autotoc_md29',1,'']]],
  ['started_19',['Started',['../index.html#autotoc_md68',1,'Getting Started'],['../ssl.html#autotoc_md73',1,'Getting Started']]],
  ['started_20with_20stepdance_20',['Getting Started with Stepdance',['../getting_started.html',1,'']]],
  ['step_20a_20sketch_20etch_20a_20sketch_21',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md59',1,'']]],
  ['step_20a_20sketch_20example_22',['Step-A-Sketch Example',['../stepasketch.html',1,'']]],
  ['step_20pulses_23',['Signals: Axis-Encoded Step Pulses',['../hardware.html#autotoc_md56',1,'']]],
  ['stepdance_24',['Stepdance',['../getting_started.html',1,'Getting Started with Stepdance'],['../stepasketch.html#autotoc_md29',1,'Start Stepdance'],['../index.html#autotoc_md67',1,'What is Stepdance?']]],
  ['stepdance_20components_25',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['stepdance_20driver_20board_26',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['stepdance_20hardware_27',['Stepdance Hardware',['../hardware.html#autotoc_md40',1,'']]],
  ['stepdance_20hardware_20documentation_28',['Stepdance Hardware Documentation',['../hardware.html',1,'']]],
  ['stepdance_20overview_29',['Stepdance Overview',['../index.html',1,'']]],
  ['stepdance_20ports_30',['Stepdance Ports',['../hardware.html#autotoc_md46',1,'Stepdance Ports'],['../hardware.html#autotoc_md54',1,'Stepdance Ports']]],
  ['stepdance_20software_20library_20documentation_31',['Stepdance Software Library Documentation',['../ssl.html',1,'']]],
  ['stepdance_20software_20library_20ssl_20documentation_32',['Stepdance Software Library (SSL) Documentation',['../index.html#autotoc_md70',1,'']]],
  ['stepper_20drivers_20and_20motor_20interfaces_33',['Stepper Drivers and Motor Interfaces',['../hardware.html#autotoc_md42',1,'']]],
  ['stepper_20motors_34',['Stepper Motors',['../stepasketch.html#autotoc_md22',1,'Enable the Stepper Motors'],['../stepasketch.html#autotoc_md4',1,'Wiring Stepper Motors']]],
  ['steps_35',['3. Next Steps',['../getting_started.html#autotoc_md39',1,'']]],
  ['support_36',['A. Install Arduino + Teensy Support',['../getting_started.html#autotoc_md35',1,'']]],
  ['supported_20hardware_37',['Supported Hardware',['../ssl.html#autotoc_md76',1,'']]],
  ['synchronous_20motion_38',['Frames: Multi-Axis Synchronous Motion',['../hardware.html#autotoc_md57',1,'']]]
];
