var searchData=
[
  ['calculate_20the_20reference_20voltage_0',['Calculate the Reference Voltage',['../stepasketch.html#autotoc_md9',1,'']]],
  ['channel_1',['Channel',['../stepasketch.html#autotoc_md16',1,'']]],
  ['channels_2',['Channels',['../md_doc_2_s_s_l_2readme__original.html#autotoc_md97',1,'Channels'],['../stepasketch.html#autotoc_md24',1,'Configure Channels']]],
  ['code_3',['Code',['../stepasketch.html#autotoc_md11',1,'']]],
  ['components_4',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['concepts_5',['Concepts',['../highspeed.html#autotoc_md55',1,'']]],
  ['configuration_6',['Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md54',1,'High-Speed Frame Configuration']]],
  ['configure_20channels_7',['Configure Channels',['../stepasketch.html#autotoc_md24',1,'']]],
  ['configure_20encoders_8',['Configure Encoders',['../stepasketch.html#autotoc_md25',1,'']]],
  ['configure_20output_20ports_9',['Configure Output Ports',['../stepasketch.html#autotoc_md23',1,'']]],
  ['configure_20position_20generator_10',['Configure Position Generator',['../stepasketch.html#autotoc_md28',1,'']]],
  ['configure_20the_20button_11',['Configure the Button',['../stepasketch.html#autotoc_md27',1,'']]],
  ['configure_20the_20kinematics_12',['Configure the Kinematics',['../stepasketch.html#autotoc_md26',1,'']]],
  ['configuring_20the_20stepdance_20driver_20board_13',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['connector_14',['Connector',['../taiss.html#autotoc_md102',1,'']]],
  ['connectors_15',['Connectors',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md37',1,'QWIIC Connectors'],['../md_doc_2readme__original.html#autotoc_md68',1,'QWIIC Connectors']]],
  ['considerations_16',['Considerations',['../highspeed.html#autotoc_md56',1,'']]],
  ['control_20knob_20mounting_17',['Control Knob Mounting',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md40',1,'Display and Control Knob Mounting'],['../md_doc_2readme__original.html#autotoc_md71',1,'Display and Control Knob Mounting']]],
  ['controller_20emulator_18',['Controller Emulator',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md53',1,'Axidraw "EBB" Controller Emulator'],['../md_doc_2readme__original.html#autotoc_md84',1,'Axidraw "EBB" Controller Emulator']]],
  ['controller_20emulator_20example_19',['Axidraw EBB Controller Emulator Example',['../ebb.html',1,'']]],
  ['current_20',['Determine the Peak Motor Current',['../stepasketch.html#autotoc_md8',1,'']]],
  ['currents_21',['Setting the Motor Driver Currents',['../stepasketch.html#autotoc_md7',1,'']]],
  ['custom_20functions_22',['Custom Functions',['../stepasketch.html#autotoc_md31',1,'']]]
];
