var searchData=
[
  ['see_20also_0',['See Also',['../highspeed.html#autotoc_md57',1,'']]],
  ['servo_20driver_1',['Hobby Servo Driver',['../hardware.html#autotoc_md45',1,'']]],
  ['servo_20motor_2',['Wiring the Servo Motor',['../stepasketch.html#autotoc_md5',1,'']]],
  ['set_20the_20reference_20voltage_3',['Set the Reference Voltage',['../stepasketch.html#autotoc_md10',1,'']]],
  ['setting_20the_20motor_20driver_20currents_4',['Setting the Motor Driver Currents',['../stepasketch.html#autotoc_md7',1,'']]],
  ['setup_5',['Setup()',['../stepasketch.html#autotoc_md21',1,'']]],
  ['signals_3a_20axis_20encoded_20step_20pulses_6',['Signals: Axis-Encoded Step Pulses',['../hardware.html#autotoc_md48',1,'']]],
  ['sketch_7',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md51',1,'']]],
  ['sketch_20etch_20a_20sketch_8',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md51',1,'']]],
  ['sketch_20example_9',['Step-A-Sketch Example',['../stepasketch.html',1,'']]],
  ['software_20library_20documentation_10',['Stepdance Software Library Documentation',['../ssl.html',1,'']]],
  ['software_20library_20ssl_20documentation_11',['Stepdance Software Library (SSL) Documentation',['../index.html#autotoc_md62',1,'']]],
  ['speed_20frame_20configuration_12',['Speed Frame Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md53',1,'High-Speed Frame Configuration']]],
  ['ssl_20documentation_13',['Stepdance Software Library (SSL) Documentation',['../index.html#autotoc_md62',1,'']]],
  ['start_20stepdance_14',['Start Stepdance',['../stepasketch.html#autotoc_md29',1,'']]],
  ['started_15',['Started',['../index.html#autotoc_md60',1,'Getting Started'],['../ssl.html#autotoc_md65',1,'Getting Started']]],
  ['step_20a_20sketch_20etch_20a_20sketch_16',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../hardware.html#autotoc_md51',1,'']]],
  ['step_20a_20sketch_20example_17',['Step-A-Sketch Example',['../stepasketch.html',1,'']]],
  ['step_20pulses_18',['Signals: Axis-Encoded Step Pulses',['../hardware.html#autotoc_md48',1,'']]],
  ['stepdance_19',['Stepdance',['../stepasketch.html#autotoc_md29',1,'Start Stepdance'],['../index.html#autotoc_md59',1,'What is Stepdance?']]],
  ['stepdance_20components_20',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['stepdance_20documentation_21',['Stepdance Documentation',['../index.html',1,'']]],
  ['stepdance_20driver_20board_22',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['stepdance_20hardware_23',['Stepdance Hardware',['../hardware.html#autotoc_md32',1,'']]],
  ['stepdance_20hardware_20documentation_24',['Stepdance Hardware Documentation',['../hardware.html',1,'']]],
  ['stepdance_20ports_25',['Stepdance Ports',['../hardware.html#autotoc_md38',1,'Stepdance Ports'],['../hardware.html#autotoc_md46',1,'Stepdance Ports']]],
  ['stepdance_20software_20library_20documentation_26',['Stepdance Software Library Documentation',['../ssl.html',1,'']]],
  ['stepdance_20software_20library_20ssl_20documentation_27',['Stepdance Software Library (SSL) Documentation',['../index.html#autotoc_md62',1,'']]],
  ['stepper_20drivers_20and_20motor_20interfaces_28',['Stepper Drivers and Motor Interfaces',['../hardware.html#autotoc_md34',1,'']]],
  ['stepper_20motors_29',['Stepper Motors',['../stepasketch.html#autotoc_md22',1,'Enable the Stepper Motors'],['../stepasketch.html#autotoc_md4',1,'Wiring Stepper Motors']]],
  ['supported_20hardware_30',['Supported Hardware',['../ssl.html#autotoc_md68',1,'']]],
  ['synchronous_20motion_31',['Frames: Multi-Axis Synchronous Motion',['../hardware.html#autotoc_md49',1,'']]]
];
