var searchData=
[
  ['see_20also_0',['See Also',['../highspeed.html#autotoc_md58',1,'']]],
  ['servo_20driver_1',['Servo Driver',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md46',1,'Hobby Servo Driver'],['../md_doc_2readme__original.html#autotoc_md77',1,'Hobby Servo Driver']]],
  ['servo_20motor_2',['Wiring the Servo Motor',['../stepasketch.html#autotoc_md5',1,'']]],
  ['set_20the_20reference_20voltage_3',['Set the Reference Voltage',['../stepasketch.html#autotoc_md10',1,'']]],
  ['setting_20the_20motor_20driver_20currents_4',['Setting the Motor Driver Currents',['../stepasketch.html#autotoc_md7',1,'']]],
  ['setup_5',['Setup()',['../stepasketch.html#autotoc_md21',1,'']]],
  ['signals_3a_20axis_20encoded_20step_20pulses_6',['Signals: Axis Encoded Step Pulses',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md49',1,'Signals: Axis-Encoded Step Pulses'],['../md_doc_2readme__original.html#autotoc_md80',1,'Signals: Axis-Encoded Step Pulses']]],
  ['sketch_7',['Sketch',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md52',1,'"Step-A-Sketch" (Etch-A-Sketch)'],['../md_doc_2readme__original.html#autotoc_md83',1,'"Step-A-Sketch" (Etch-A-Sketch)']]],
  ['sketch_20etch_20a_20sketch_8',['Sketch Etch A Sketch',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md52',1,'"Step-A-Sketch" (Etch-A-Sketch)'],['../md_doc_2readme__original.html#autotoc_md83',1,'"Step-A-Sketch" (Etch-A-Sketch)']]],
  ['sketch_20example_9',['Step-A-Sketch Example',['../stepasketch.html',1,'']]],
  ['software_20library_20documentation_10',['Stepdance Software Library Documentation',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/SSL/readme.md#autotoc_md85',1,'']]],
  ['software_20library_20user_20manual_11',['Stepdance Software Library User Manual',['../md_doc_2_s_s_l_2readme__original.html',1,'']]],
  ['speed_20frame_20configuration_12',['Speed Frame Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md54',1,'High-Speed Frame Configuration']]],
  ['start_20stepdance_13',['Start Stepdance',['../stepasketch.html#autotoc_md29',1,'']]],
  ['started_14',['Getting Started',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/SSL/readme.md#autotoc_md88',1,'']]],
  ['step_20a_20sketch_20etch_20a_20sketch_15',['Step A Sketch Etch A Sketch',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md52',1,'"Step-A-Sketch" (Etch-A-Sketch)'],['../md_doc_2readme__original.html#autotoc_md83',1,'"Step-A-Sketch" (Etch-A-Sketch)']]],
  ['step_20a_20sketch_20example_16',['Step-A-Sketch Example',['../stepasketch.html',1,'']]],
  ['step_20pulses_17',['Step Pulses',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md49',1,'Signals: Axis-Encoded Step Pulses'],['../md_doc_2readme__original.html#autotoc_md80',1,'Signals: Axis-Encoded Step Pulses']]],
  ['stepdance_18',['Stepdance',['../stepasketch.html#autotoc_md29',1,'Start Stepdance'],['../index.html#autotoc_md60',1,'What is Stepdance?'],['../md_doc_2readme__original.html#autotoc_md63',1,'What is Stepdance?']]],
  ['stepdance_20components_19',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['stepdance_20documentation_20',['Stepdance Documentation',['../md_doc_2readme__original.html',1,'Stepdance Documentation'],['../index.html',1,'Stepdance Documentation']]],
  ['stepdance_20driver_20board_21',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['stepdance_20hardware_22',['Stepdance Hardware',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md33',1,'Stepdance Hardware'],['../md_doc_2readme__original.html#autotoc_md64',1,'Stepdance Hardware']]],
  ['stepdance_20hardware_20documentation_23',['Stepdance Hardware Documentation',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md32',1,'']]],
  ['stepdance_20ports_24',['Stepdance Ports',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md39',1,'Stepdance Ports'],['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md47',1,'Stepdance Ports'],['../md_doc_2readme__original.html#autotoc_md70',1,'Stepdance Ports'],['../md_doc_2readme__original.html#autotoc_md78',1,'Stepdance Ports']]],
  ['stepdance_20software_20library_20documentation_25',['Stepdance Software Library Documentation',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/SSL/readme.md#autotoc_md85',1,'']]],
  ['stepdance_20software_20library_20user_20manual_26',['Stepdance Software Library User Manual',['../md_doc_2_s_s_l_2readme__original.html',1,'']]],
  ['stepper_20drivers_20and_20motor_20interfaces_27',['Stepper Drivers and Motor Interfaces',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md35',1,'Stepper Drivers and Motor Interfaces'],['../md_doc_2readme__original.html#autotoc_md66',1,'Stepper Drivers and Motor Interfaces']]],
  ['stepper_20motors_28',['Stepper Motors',['../stepasketch.html#autotoc_md22',1,'Enable the Stepper Motors'],['../stepasketch.html#autotoc_md4',1,'Wiring Stepper Motors']]],
  ['supported_20hardware_29',['Supported Hardware',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/SSL/readme.md#autotoc_md91',1,'']]],
  ['synchronous_20motion_30',['Synchronous Motion',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/hardware/readme.md#autotoc_md50',1,'Frames: Multi-Axis Synchronous Motion'],['../md_doc_2readme__original.html#autotoc_md81',1,'Frames: Multi-Axis Synchronous Motion']]]
];
