var searchData=
[
  ['see_20also_0',['See Also',['../highspeed.html#autotoc_md36',1,'']]],
  ['servo_20driver_1',['Hobby Servo Driver',['../index.html#autotoc_md52',1,'']]],
  ['servo_20motor_2',['Wiring the Servo Motor',['../stepasketch.html#autotoc_md5',1,'']]],
  ['set_20the_20reference_20voltage_3',['Set the Reference Voltage',['../stepasketch.html#autotoc_md10',1,'']]],
  ['setting_20the_20motor_20driver_20currents_4',['Setting the Motor Driver Currents',['../stepasketch.html#autotoc_md7',1,'']]],
  ['setup_5',['Setup()',['../stepasketch.html#autotoc_md21',1,'']]],
  ['signals_3a_20axis_20encoded_20step_20pulses_6',['Signals: Axis-Encoded Step Pulses',['../index.html#autotoc_md55',1,'']]],
  ['sketch_7',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../index.html#autotoc_md58',1,'']]],
  ['sketch_20etch_20a_20sketch_8',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../index.html#autotoc_md58',1,'']]],
  ['sketch_20example_9',['Step-A-Sketch Example',['../stepasketch.html',1,'']]],
  ['software_20library_20user_20manual_10',['Stepdance Software Library User Manual',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/SSL/readme.md#autotoc_md60',1,'']]],
  ['speed_20frame_20configuration_11',['Speed Frame Configuration',['../highspeed.html',1,'High-Speed Frame Configuration'],['../highspeed.html#autotoc_md32',1,'High-Speed Frame Configuration']]],
  ['start_20stepdance_12',['Start Stepdance',['../stepasketch.html#autotoc_md29',1,'']]],
  ['step_20a_20sketch_20etch_20a_20sketch_13',['&quot;Step-A-Sketch&quot; (Etch-A-Sketch)',['../index.html#autotoc_md58',1,'']]],
  ['step_20a_20sketch_20example_14',['Step-A-Sketch Example',['../stepasketch.html',1,'']]],
  ['step_20pulses_15',['Signals: Axis-Encoded Step Pulses',['../index.html#autotoc_md55',1,'']]],
  ['stepdance_16',['Stepdance',['../stepasketch.html#autotoc_md29',1,'Start Stepdance'],['../index.html#autotoc_md38',1,'What is Stepdance?']]],
  ['stepdance_20components_17',['Define all stepdance components',['../stepasketch.html#autotoc_md14',1,'']]],
  ['stepdance_20documentation_18',['Stepdance Documentation',['../index.html',1,'']]],
  ['stepdance_20driver_20board_19',['Configuring the Stepdance Driver Board',['../stepasketch.html#autotoc_md2',1,'']]],
  ['stepdance_20hardware_20',['Stepdance Hardware',['../index.html#autotoc_md39',1,'']]],
  ['stepdance_20ports_21',['Stepdance Ports',['../index.html#autotoc_md45',1,'Stepdance Ports'],['../index.html#autotoc_md53',1,'Stepdance Ports']]],
  ['stepdance_20software_20library_20user_20manual_22',['Stepdance Software Library User Manual',['..//Users/jenniferjacobs/Documents/research/code/stepdance_research/stepdance/doc/SSL/readme.md#autotoc_md60',1,'']]],
  ['stepper_20drivers_20and_20motor_20interfaces_23',['Stepper Drivers and Motor Interfaces',['../index.html#autotoc_md41',1,'']]],
  ['stepper_20motors_24',['Stepper Motors',['../stepasketch.html#autotoc_md22',1,'Enable the Stepper Motors'],['../stepasketch.html#autotoc_md4',1,'Wiring Stepper Motors']]],
  ['synchronous_20motion_25',['Frames: Multi-Axis Synchronous Motion',['../index.html#autotoc_md56',1,'']]]
];
